/*
   (c) NXP B.V. 2009-2015. All rights reserved.

   Disclaimer
   1. The NXP Software/Source Code is provided to Licensee "AS IS" without any
      warranties of any kind. NXP makes no warranties to Licensee and shall not
      indemnify Licensee or hold it harmless for any reason related to the NXP
      Software/Source Code or otherwise be liable to the NXP customer. The NXP
      customer acknowledges and agrees that the NXP Software/Source Code is
      provided AS-IS and accepts all risks of utilizing the NXP Software under
      the conditions set forth according to this disclaimer.

   2. NXP EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING,
      BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
      FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF INTELLECTUAL PROPERTY
      RIGHTS. NXP SHALL HAVE NO LIABILITY TO THE NXP CUSTOMER, OR ITS
      SUBSIDIARIES, AFFILIATES, OR ANY OTHER THIRD PARTY FOR ANY DAMAGES,
      INCLUDING WITHOUT LIMITATION, DAMAGES RESULTING OR ALLEGDED TO HAVE
      RESULTED FROM ANY DEFECT, ERROR OR OMMISSION IN THE NXP SOFTWARE/SOURCE
      CODE, THIRD PARTY APPLICATION SOFTWARE AND/OR DOCUMENTATION, OR AS A
      RESULT OF ANY INFRINGEMENT OF ANY INTELLECTUAL PROPERTY RIGHT OF ANY
      THIRD PARTY. IN NO EVENT SHALL NXP BE LIABLE FOR ANY INCIDENTAL,
      INDIRECT, SPECIAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES
      (INCLUDING LOST PROFITS) SUFFERED BY NXP CUSTOMER OR ITS SUBSIDIARIES,
      AFFILIATES, OR ANY OTHER THIRD PARTY ARISING OUT OF OR RELATED TO THE NXP
      SOFTWARE/SOURCE CODE EVEN IF NXP HAS BEEN ADVISED OF THE POSSIBILITY OF
      SUCH DAMAGES.

   3. NXP reserves the right to make changes to the NXP Software/Sourcecode any
      time, also without informing customer.

   4. Licensee agrees to indemnify and hold harmless NXP and its affiliated
      companies from and against any claims, suits, losses, damages,
      liabilities, costs and expenses (including reasonable attorney's fees)
      resulting from Licensee's and/or Licensee customer's/licensee's use of the
      NXP Software/Source Code.

 */


/*
 * $Revision: 315 $
 * $URL: https://www.collabnet.nxp.com/svn/reference_designs/door_handle/trunk/D%20Software/onhost/DHRD%20V2_0/S12ZVL128/phhwConfig.c $
 */

/*----------------------------------------------------------------------------------------------
 * Includes
 ---------------------------------------------------------------------------------------------*/
#include "Cpu.h"
#include <ph_TypeDefs.h>
#include <ph_Status.h>
#include <phhalHw.h>
#include <phbalReg.h>
#include <phbalReg_Stub.h>
#include <ph_NxpBuild.h>
#include <ph_Status.h>
#include <phOsal.h>

#include "SPI.h"
#include "PIN_RESET.h"
#include "LED_BIT.h"
#include "PIN_SSEL.h"
#include "LED_R_BIT.h"
#include "EN_PWR.h"

#include "phhwConfig.h"


/*----------------------------------------------------------------------------------------------
 * Local macros and definitions
 ---------------------------------------------------------------------------------------------*/


/*----------------------------------------------------------------------------------------------
 * Global variables
 * -------------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------------
 * Local variables
 * -------------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------------
 * Local function declaration
 ---------------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------------
 * Global function prototypes
 ---------------------------------------------------------------------------------------------*/


/* **************************************
 * Initialize interface link            *
 * **************************************/

/* =============================================================================================
 * Function:	Set_Interface_Link
 *
 * brief:
 *   Initialize interface link
 *   GPIOSetDir sets the direction in GPIO port.
 *   1 out, 0 input
 *
 *   GPIOSetValue sets/clears a bitvalue in a specific bit position
 *   in GPIO portX(X is the port number.)
 *   Our PN512 will act in slave mode. START and STOP conditions are
 *   generated by the master.
 *
 * -------------------------------------------------------------------------------------------*/
void Set_Interface_Link(void)
{
	/*** Processor Expert internal initialization. DON'T REMOVE THIS CODE!!! ***/
	PE_low_level_init();
	/*** End of Processor Expert internal initialization.                    ***/
	
#if defined NXPBUILD__PHHAL_HW_NCx3320
#ifdef SPI_USED

    /* Select SPI link -> IFSEL0 = 0 & IFSEL1 = 1 */
	/* On the NXP Door Handle Reference design, the SPI is hardware selected*/
    /* IFSEL0 = 0 */
    //PIN_IFSEL0_ClrVal();

    /* IFSEL1 = 1 */
    //PIN_IFSEL1_SetVal();
	
	/* Enable power */
	EN_PWR_SetVal();
#endif /* SPI_USED */
#endif /* NXPBUILD__PHHAL_HW_NCx3320 */
}
/*==============================================================================================
 * Function:	Reset_reader_device
 *
 * brief:	This function resets an attached reader IC. In PIN_RESET macro is a correct pin .
 *
 * -------------------------------------------------------------------------------------------*/
void Reset_reader_device(void)
{
uint32_t volatile i;

#if defined NXPBUILD__PHHAL_HW_NCx3320
	/* send the reset pulse 0-1-0 to reset device */
	/* RSET signal low - PDOWN to '0' */
	PIN_RESET_ClrVal();


	Cpu_Delay100US(12); /* delay of ~1,2 ms */

	/* RSET signal high to reset the NCx3320 IC - PDOWN to '1' */
    PIN_RESET_SetVal();

	
	Cpu_Delay100US(12); /* delay of ~1,2 ms */

	/* RSET signal low - PDOWN to '0' */
	PIN_RESET_ClrVal();

	Cpu_Delay100US(12); /* delay of ~1,2 ms */
#endif

}
/* **************************************
 * handle GPIO                          *
 * **************************************/

/*==============================================================================================
 * Function:	GPIO_Init
 *
 * brief:
 *
 * -------------------------------------------------------------------------------------------*/
void GPIO_Init(void)
    {
    /* there is a different name for the GPIO driver module for each LPC processor which comes
     * from drivers.
     * GPIO interface is consolidated via this function calling.
     */

    //GPIOInit();
    }

/*==============================================================================================
 * Function:	LedOn
 *
 * brief:	switch the LED on
 *
 * -------------------------------------------------------------------------------------------*/
void LedOn(void)
    {
	LED_BIT_ClrVal();
    }

/*==============================================================================================
 * Function:	LedOff
 *
 * brief:	switch the LED off
 *
 * -------------------------------------------------------------------------------------------*/
void LedOff(void)
    {
	LED_BIT_SetVal();
    }

/*----------------------------------------------------------------------------------------------
 * End of file
 ---------------------------------------------------------------------------------------------*/

